---
- hosts: raspberry-pi
  remote_user: root
  gather_facts: False
  tasks:
    - name: install python 2
      raw: pacman -S --noconfirm --quiet --needed python2

- hosts: raspberry-pi
  remote_user: root
  roles:
    - common
