---
# file: site.yml

- hosts: all
  sudo: yes

  roles:
    - common
    - rbpconfig

- hosts: xbmc
  sudo: yes

  roles:
    - xbmc

- hosts: mopidy
  sudo: yes

  roles:
    - mopidy

- hosts: syncthing
  sudo: yes

  roles:
    - syncthing

- hosts: btsync
  sudo: yes

  roles:
    - btsync