---
# file: site.yml

- hosts: all
  sudo: yes

  roles:
    - common
    - rbpconfig

- hosts: kodi
  sudo: yes
  roles:
    - {role: kodi, tags: kodi}

- hosts: mopidy
  sudo: yes
  roles:
    - {role: mopidy, tags: mopidy}
