---
- include: libspotify.yml

- name: update repo cache
  command: pacman -Sy

- name: install mopidy
  command: packer -S --noedit --noconfirm {{ item }}
  with_items:
    - gcc
    - mopidy
    - mopidy-spotify

- name: create home
  file: path={{mopidy_home}} state=directory owner=mopidy group=mopidy

- name: change home
  user: name=mopidy home={{mopidy_home}} state=present

- name: ensure config folder (.config)
  file: path={{mopidy_home}}/.config state=directory owner=mopidy group=mopidy

- name: ensure config folder (.config/mopidy)
  file: path={{mopidy_home}}/.config/mopidy state=directory owner=mopidy group=mopidy

- name: update default config
  template: src=config.j2 dest={{mopidy_home}}/.config/mopidy/mopidy.conf owner=mopidy group=mopidy
  notify: restart mopidy

- name: enable xbmc service
  service: name=mopidy enabled=yes state=started
