---
- name: update repo cache
  command: pacman -Sy

- name: install build dependencies
  pacman: name={{item}} state=present
  with_items:
    - gcc
    - make
    - binutils

- name: install mopidy
  command: apacman -S --needed --noedit --noconfirm {{ item }}
  with_items:
    - libspotify
    - mopidy
    - mopidy-spotify
    - mopidy-moped  # webinterface
    - mopidy-mopify  # webinterface

- name: update default config
  template: src=config.j2 dest=/etc/mopidy/mopidy.conf owner=mopidy group=mopidy
  notify: restart mopidy

- name: enable mopidy service
  service: name=mopidy enabled=yes state=started
