---

- name: packer | check wether installed
  stat: path=/usr/bin/packer
  register: check_path

- name: packer | install build requirements
  pacman: name={{item}} state=installed
  with_items:
    - jshon
    - expac
    - git
    - binutils
  when: check_path.stat.exists == false

- name: packer | create temp folder
  file: path=/tmp/packer state=directory
  when: check_path.stat.exists == false

- name: packer | download PKGBUILD
  get_url: url=https://aur.archlinux.org/packages/pa/packer/PKGBUILD dest=/tmp/packer/
  when: check_path.stat.exists == false

- name: packer | build
  command: chdir=/tmp/packer/ makepkg -f --asroot
  when: check_path.stat.exists == false

- name: packer | install
  shell: pacman -U --noconfirm /tmp/packer/packer-*.pkg.tar.xz
  when: check_path.stat.exists == false

- name: packer | cleanup
  file: path=/tmp/packer state=absent
  when: check_path.stat.exists == false
